######################################################################################
# Repository: https://github.com/roacn/Githubtogitx
# Author: Ss.
######################################################################################

name: Sync via Git

on:
  #push:
    #branches: [master]
  workflow_dispatch:
    inputs:
      FORCE_MIRROR:
        description: '开启强制同步至Gitx'
        required: false
        default: false
        type: boolean
      ENABLE_SSH:
        description: '开启SSH连接'
        required: false
        default: false
        type: boolean
        
  # 启动定时请取消下面的“#”
  schedule:
   - cron: 30 4-16/6 * * 1-5
   - cron: 30 0-16/8 * * 0,6
     
jobs:
  git-mirror:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id
    strategy:
      fail-fast: false
      matrix:
        include:
            # 同步多个仓库，请按要求添加即可
            # 替换为需要同步的 GitHub 源仓库地址
          - githubUserName: roacn
            githubRepoName: build-actions
            # 替换为目标仓库地址
            destHostName: gitee.com
            destUserName: stanlyshi
            destRepoName: build-actions
          - githubUserName: roacn
            githubRepoName: openwrt-packages
            destHostName: gitee.com
            destUserName: stanlyshi
            destRepoName: openwrt-packages
          - githubUserName: roacn
            githubRepoName: pve
            destHostName: gitee.com
            destUserName: stanlyshi
            destRepoName: pve
          - githubUserName: stanlyshi
            githubRepoName: tvbox-cfg
            destHostName: gitcode.com
            destUserName: roa
            destRepoName: roas
    steps:
      - name: Get Commit Hash
        id: getHash
        run: |
          githubRepoDir=${{ matrix.githubUserName }}-${{ matrix.githubRepoName }}
          echo "githubRepoDir=$githubRepoDir" >> $GITHUB_ENV
          git clone --depth 1 https://github.com/${{ matrix.githubUserName }}/${{ matrix.githubRepoName }} $githubRepoDir
          cd $githubRepoDir
          echo "commitHash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          rm -rf $githubRepoDir
          
      - name: Compare Commit Hash
        id: cacheHash
        uses: actions/cache@v3
        with:
          path: .commitHash
          key: ${{ env.githubRepoDir }}-${{ steps.getHash.outputs.commitHash }}
          
      - name: Generate Commit Hash
        if: steps.cacheHash.outputs.cache-hit != 'true'
        run: |
          echo ${{ steps.getHash.outputs.commitHash }} | tee .commitHash
          
      - name: Github Sync to gitx
        continue-on-error: true
        if: steps.cacheHash.outputs.cache-hit != 'true' || github.event.inputs.FORCE_MIRROR == 'true'
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:${{ matrix.githubUserName }}/${{ matrix.githubRepoName }}.git"
          destination-repo: "git@${{ matrix.destHostName }}:${{ matrix.destUserName }}/${{ matrix.destRepoName }}.git"

      - name: SSH via tmate
        if: github.event.inputs.ENABLE_SSH == 'true'
        uses: P3TERX/ssh2actions@main
        
      - name: Delete Older Workflow Runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 3
          
