######################################################################################
# Repository: https://github.com/roacn/GithubtoGitee
# Author: Ss.
######################################################################################

name: Sync to Gitee

on:
  workflow_dispatch:
    inputs:
      FORCE_MIRROR:
        description: '开启强制同步至Gitee'
        required: false
        default: false
        type: boolean
      ENABLE_SSH:
        description: '开启SSH连接'
        required: false
        default: false
        type: boolean
        
  # 启动定时请取消下面的“#”
  schedule:
   - cron: 30 4-16/6 * * 1-5
   - cron: 30 0-16/8 * * 0,6
   
jobs:
  git-mirror:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id
    strategy:
      fail-fast: false
      matrix:
        include:
            # 同步多个仓库，按格式在后面追加填写
            # github_repo的值，替换为待同步的GitHub源仓库地址；
            # dest_repo的值，替换为Gitee目标仓库地址；
          - github_repo: roacn/build-actions
            dest_hostname: gitee.com
            dest_repo: stanlyshi/build-actions
          - github_repo: roacn/openwrt-packages
            dest_hostname: gitee.com
            dest_repo: stanlyshi/openwrt-packages
          - github_repo: roacn/pve
            dest_hostname: gitee.com
            dest_repo: stanlyshi/pve
          - github_repo: stanlyshi/tvbox-cfg
            dest_hostname: gitcode.com
            dest_repo: roa/roas
            
    steps:
      - name: Get Commit Hash
        id: getHash
        run: |
          github_repo_dir=$(echo ${{ matrix.github_repo }} | sed 's|/|-|')
          echo "github_repo_dir=$github_repo_dir" >> $GITHUB_ENV
          git clone --depth 1 https://github.com/${{ matrix.github_repo }} $github_repo_dir
          cd $github_repo_dir
          echo "commitHash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          rm -rf $github_repo_dir
          
      - name: Compare Commit Hash
        id: cacheHash
        uses: actions/cache@v3
        with:
          path: .commitHash
          key: ${{ env.github_repo_dir }}-${{ steps.getHash.outputs.commitHash }}
          
      - name: Generate Commit Hash
        if: steps.cacheHash.outputs.cache-hit != 'true'
        run: |
          echo ${{ steps.getHash.outputs.commitHash }} | tee .commitHash
          
      - name: Github Sync to Gitee
        continue-on-error: true
        if: steps.cacheHash.outputs.cache-hit != 'true' || github.event.inputs.FORCE_MIRROR == 'true'
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:${{ matrix.github_repo }}.git"
          destination-repo: "git@${{ matrix.dest_hostname }}:${{ matrix.dest_repo }}.git"

      - name: SSH via tmate
        if: github.event.inputs.ENABLE_SSH == 'true'
        uses: P3TERX/ssh2actions@main
