######################################################################################
# Repository: https://github.com/roacn/GithubtoGitee
# Author: Ss.
######################################################################################

name: Sync to Gitee

on:
  #push:
    #branches: [master]
  workflow_dispatch:
    inputs:
      FORCE_MIRROR:
        description: '开启强制同步至Gitee'
        required: false
        default: false
        type: boolean
      ENABLE_SSH:
        description: '开启SSH连接'
        required: false
        default: false
        type: boolean
        
  # 启动定时请取消下面的“#”
  schedule:
   - cron: 30 4-16/6 * * 1-5
   - cron: 30 0-16/8 * * 0,6
   
env:
  DESTINATION_HOSTNAME: gitee.com
  
jobs:
  git-mirror:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id
    strategy:
      fail-fast: false
      matrix:
        include:
            # 同步多个仓库，请按要求添加即可
            # githubRepo 替换为待同步的 GitHub 源仓库地址；destRepo 替换为 Gitee 目标仓库地址
          - githubRepo: roacn/build-actions
            destRepo: stanlyshi/build-actions
          - githubRepo: roacn/openwrt-packages
            destRepo: stanlyshi/openwrt-packages
          - githubRepo: roacn/pve
            destRepo: stanlyshi/pve
            
    steps:
      - name: Get Commit Hash
        id: getHash
        run: |
          githubRepoDir=$(echo ${{ matrix.githubRepo }} | sed 's|/|-|')
          echo "githubRepoDir=$githubRepoDir" >> $GITHUB_ENV
          git clone --depth 1 https://github.com/${{ matrix.githubRepo }} $githubRepoDir
          cd $githubRepoDir
          echo "commitHash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          rm -rf $githubRepoDir
          
      - name: Compare Commit Hash
        id: cacheHash
        uses: actions/cache@v3
        with:
          path: .commitHash
          key: ${{ env.githubRepoDir }}-${{ steps.getHash.outputs.commitHash }}
          
      - name: Generate Commit Hash
        if: steps.cacheHash.outputs.cache-hit != 'true'
        run: |
          echo ${{ steps.getHash.outputs.commitHash }} | tee .commitHash
          
      - name: Github Sync to Gitee
        continue-on-error: true
        if: steps.cacheHash.outputs.cache-hit != 'true' || github.event.inputs.FORCE_MIRROR == 'true'
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:${{ matrix.githubRepo }}.git"
          destination-repo: "git@${{ env.DESTINATION_HOSTNAME }}:${{ matrix.destRepo }}.git"

      - name: SSH via tmate
        if: github.event.inputs.ENABLE_SSH == 'true'
        uses: P3TERX/ssh2actions@main
        
      - name: Delete Older Workflow Runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 3
          
